@Library('shared-library') _

node('ws') {

env.COMPONENT="shipping"   // this is how variable is declared and this we can call from shared library
env.APPTYPE="java"
env.TAG_NAME="latest"

docker()

      
}