@Library('shared-library') _

env.COMPONENT="SHIPPING"   // this is how variable is declared and this we can call from shared library

// call is the function that will be called by default. so, we are declaring the entire pipeline in the vars/java.groovy

java()